# Generated by Django 6.0.7 on 2026-09-05 12:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.CharField(help_text='e.g: men steel, women steel, smart', max_length=100)),
                ('product_type', models.CharField(default="Men's Stainless Steel", max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('old_price', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_percent', models.CharField(blank=True, max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.7'), max_digits=2)),
                ('icon_name', models.CharField(default='watch', help_text='bootstrap icon name without bi-', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Vantico', max_length=100)),
                ('site_meta_title', models.CharField(blank=True, max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('site_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('site_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('site_url', models.URLField(default='https://example.com')),
                ('site_author', models.CharField(blank=True, max_length=100, null=True)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site_logo/')),
                ('site_logo_dark', models.ImageField(blank=True, null=True, upload_to='site_logo/')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='site_favicon/')),
                ('site_og_image', models.ImageField(blank=True, null=True, upload_to='site_seo/')),
                ('site_theme_color', models.CharField(default='#000000', max_length=7)),
                ('site_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('site_whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('site_address', models.TextField(blank=True, null=True)),
                ('site_map_embed', models.TextField(blank=True, null=True)),
                ('site_business_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('site_language', models.CharField(default='en', max_length=50)),
                ('site_currency', models.CharField(default='PKR', max_length=10)),
                ('site_currency_symbol', models.CharField(default='Rs.', max_length=5)),
                ('site_timezone', models.CharField(default='Asia/Karachi', max_length=50)),
                ('site_pagination_count', models.PositiveIntegerField(default=12)),
                ('site_social_links', models.JSONField(blank=True, default=dict)),
                ('site_google_analytics_id', models.CharField(blank=True, max_length=100, null=True)),
                ('site_google_tag_manager_id', models.CharField(blank=True, max_length=100, null=True)),
                ('site_facebook_pixel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('site_google_search_console', models.CharField(blank=True, max_length=255, null=True)),
                ('site_robots_txt', models.TextField(blank=True, default='User-agent: *\nAllow: /', null=True)),
                ('site_header_script', models.TextField(blank=True, null=True)),
                ('site_footer_script', models.TextField(blank=True, null=True)),
                ('site_custom_css', models.TextField(blank=True, null=True)),
                ('site_custom_js', models.TextField(blank=True, null=True)),
                ('site_chatbot_code', models.TextField(blank=True, null=True)),
                ('site_annocement_text', models.TextField(blank=True, null=True)),
                ('site_annocement_link', models.URLField(blank=True, null=True)),
                ('site_annocement_status', models.BooleanField(default=False)),
                ('site_maintenance_mode', models.BooleanField(default=False)),
                ('site_maintenance_message', models.TextField(blank=True, default='We are under maintenance.', null=True)),
                ('site_footer_text', models.TextField(blank=True, null=True)),
                ('site_copyright_text', models.TextField(default='© 2026 All Rights Reserved.')),
                ('site_enable_registration', models.BooleanField(default=True)),
                ('site_enable_blog', models.BooleanField(default=True)),
                ('site_enable_shop', models.BooleanField(default=False)),
                ('site_recaptcha_site_key', models.CharField(blank=True, max_length=255, null=True)),
                ('site_recaptcha_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='lastapp.footercolumn')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('total_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
